#!/bin/bash 


DIRTMPSHARED="/tmp/dir_shared/shared_folder"
for USERDEST in $(cat /tmp/user) ; do
       echo "user $USERDEST"

#   LISTAR PASTAS COMPARTILHADAS NA CONTA
ZMLISTFOLDER="$ZMMAILBOX -z -m $USERDEST gaf | grep \( |awk '{\$1=\$2=\$3=\$4=\"\"; print \$0}'  |  sed 's/:/|/g' | sed 's/ (/|/g' | sed 's/)/|/g' "

$CONNECT $ZMLISTFOLDER > ${DIRTMPSHARED}_$USERDEST
sed -i 's/    //'  ${DIRTMPSHARED}_${USERDEST}
FINDTEXT="cat ${DIRTMPSHARED}_$USERDEST"

        if [ -z "$FINDTEXT" ]; then

echo " User $USERDEST does not has shared folder "


        else

                cat ${DIRTMPSHARED}_$USERDEST | awk -F"|" '{print $1}' | while read DIRDEST ; do
                         IDORIG=$(cat ${DIRTMPSHARED}_${USERDEST} | grep "$DIRDEST" | awk -F"|" '{print $3}' )
                        ACCOUNTORIG=$(cat ${DIRTMPSHARED}_$USERDEST | grep "$DIRDEST" | awk -F"|" '{print $2}' )
			MODIFYID="$ZMMAILBOX -z -m $ACCOUNTORIG gaf | awk '(\$1 == $IDORIG ) {\$1=\$2=\$3=\$4=\"\"; print \$0}'"
			TRADEID=$($CONNECT $MODIFYID < /dev/null)
		
			echo " $ZMMAILBOX -z -m "${USERDEST}" df "$DIRDEST" "
			 $ZMMAILBOX -z -m "${USERDEST}" df "$DIRDEST" 
			echo "$ZMMAILBOX -z -m ${ACCOUNTORIG} "${TRADEID}" account ${USERDEST} rwixa "
			$ZMMAILBOX -z -m ${ACCOUNTORIG} "${TRADEID}" account ${USERDEST} rwixa 


			echo "$ZMMAILBOX -z -m ${USERDEST} cm "${DIRDEST}" ${ACCOUNTORIG} "${TRADEID}" "
			$ZMMAILBOX -z -m ${USERDEST} cm "${DIRDEST}" ${ACCOUNTORIG} "${TRADEID}" 

		 done

        fi

done

